---
- name: Atualiza cache e instala pacotes básicos
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - snapd
      - python3
      - python3-pip
      - git
      - vim
    update_cache: yes
    state: present

- name: Adiciona chave GPG do Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adiciona repositório do Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Instala Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
    state: present

- name: Cria diretório de configuração do containerd
  file:
    path: /etc/docker
    state: directory

- name: Copia daemon.json do Docker
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'

- name: Reinicia Docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Cria diretório de instalação do K3s
  file:
    path: /usr/local/bin
    state: directory
    mode: '0755'

- name: Instala o K3s como servidor
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -
  args:
    creates: /etc/systemd/system/k3s.service

# - name: Cria diretório de configuração do K3s
#   file:
#     path: /etc/rancher/k3s
#     state: directory
#     mode: '0755'

# - name: Copia registries.yaml
#   copy:
#     src: files/registries.yaml.j2
#     dest: /etc/rancher/k3s/registries.yaml
#     owner: root
#     group: root
#     mode: '0644'

# - name: Copia k3s.service.env
#   template:
#     src: files/k3s.service.env.j2
#     dest: /etc/systemd/system/k3s.service.env
#     owner: root
#     group: root
#     mode: '0600'

# - name: Copia k3s.service
#   copy:
#     src: files/k3s.service
#     dest: /etc/systemd/system/k3s.service
#     owner: root
#     group: root
#     mode: '0644'

# - name: Recarrega daemon do systemd
#   command: systemctl daemon-reexec

- name: Ativa e inicia K3s
  service:
    name: k3s
    state: started
    enabled: yes

# - name: Substitui IP no kubeconfig
#   replace:
#     path: /etc/rancher/k3s/k3s.yaml
#     regexp: 'server: https://[0-9\.]+:6443'
#     replace: 'server: https://{{ ansible_host }}:6443'

- name: Aplica o ingress-nginx
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.2/deploy/static/provider/cloud/deploy.yaml

- name: Copia ingress-nginx.yaml adicional
  copy:
    src: files/ingress-nginx.yaml
    dest: /root/
    mode: '0644'

- name: Aplica ingress-nginx.yaml
  command: kubectl apply -f /root/ingress-nginx.yaml

- name: Cria diretório de homolog
  file:
    path: /root/homolog
    state: directory
    mode: '0755'

- name: Copia manifestos da homologação
  copy:
    src: manifestos/homolog/
    dest: /root/homolog/
    mode: '0644'
