---
- name: Incluir tasks para configurar sonarqube
  hosts: sonarqube
  become: true
  tasks:
    - include_tasks: tasks/sonarqube.yml


- name: Incluir tasks para configurar nexus
  hosts: nexus
  become: true
  tasks:
    - include_tasks: tasks/nexus.yml


- name: Incluir tasks para configurar k3s
  hosts: k3s
  become: true
  tasks:
    - include_tasks: tasks/k3s.yml

# - name: Incluir tasks para configurar gitlab-ci
#   hosts: gitlab-ci
#   become: true
#   tasks:
#     - include_tasks: tasks/gitlab-ci.yml